// <auto-generated />
namespace HospitalMangementApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _11_11_1250 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11_11_1250));
        
        string IMigrationMetadata.Id
        {
            get { return "201511110651048_11_11_12.50"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
